### ISSUE TITLE
Inconsistency between pretrain.sh and finetune script

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#2]
In the pretrain script, the mm_projector_type is unset and is defaulted into "linear". However, in the finetune script this value is set to "mlp2x_gelu", which causes a conflict in loading the corresponding weights. Which configuration is used for the actual model?

**Comment by xjjxmu** [comment]
Thank you for your attention. For the chat model, we used “mlp2x_gelu”, and for fine-tuning on downstream tasks, we used a simple linear projector.

**Comment by xingyifei2016** [comment]
Sorry, I didn't quite understand your reply. Shouldn't the chat model have the same multi-modal MLP projector for pretraining and finetuning? How can they be different according to different tasks?

**Comment by xingyifei2016** [comment]
也可以用中文说，麻烦作者了，就是那个mmprojector我发现pretrain的config用的是一个线性层，但是finetune里面的mmprojector用的是两个线性层，这就导致了之前pretrain训练的权重无法被正常加载到finetune的script里面，会报错

**Comment by xjjxmu** [comment]
可能语言习惯上有歧义导致有误解。我这里的finetune指的是在sqa等下游任务上直接进行微调的意思，对应于scripts中的sqa，而chat模型指的就是sft后得到的模型，对应于scripts中的sft。

对于前者我们简单的使用一层线性层作为projector，对于后者，我们跟随llava-1.5的范式使用的是mlp2x_gelu。如果你是想做sft，应该要把pretrain.sh中的projector改为对应的mlp2x_gelu类型。

**Comment by xingyifei2016** [comment]
好的，谢谢作者
