### ISSUE TITLE
Plan to release the qlora version of model

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#4]
Hello authors, again I really appreciate the great work. When will the training code for the qlora version of the model (as reported by the paper) be released as to make comparisons with your main model? Thank you!

**Comment by xjjxmu** [comment]
We have directly adopted the code provided by LLaVA for QLoRA. You can reproduce it by following their instructions.

**Comment by xingyifei2016** [comment]
Thank you, that answers my question.
