### ISSUE TITLE
Problem with Zero3 Optimization

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#5]
Hello authors, when trying to reproduce the results in scripts/sft/chat_for_13b_v1_5.sh, in the last segment of the code with zero3 optimization, the code fails to retrieve the model weights in zero3 optimization, causing an error. How do you retrieve weights with the zero3 optimization? The replace_quantization function utilizes the shape of each weight to construct the quantization layers, and when I do model.model.layers[0].self_attn.q_proj.weight in zero3, it prints Parameter containing: tensor([], device='cuda:0', dtype=torch.bfloat16, requires_grad=True).

**Comment by xjjxmu** [comment]
This is because DeepSpeed zero3 only creates parameters when loading weights. We recommend using zero2, or you can refer to this [issue](https://github.com/THUDM/ChatGLM-6B/issues/530) to adapt zero3.

**Comment by xjjxmu** [comment]
If you have any other questions, feel free to open this issue.
