### ISSUE TITLE
How do you use the model to generate an output in quantized state?

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#6]
Hello authors, thanks again for the excellent work. Say that I have a completed model ckpt and want to load it as:
model = LlavaLlamaForCausalLM.from_pretrained("./checkpoints/llava-v1.5-vicuna-13b-v1.5-13b-chat-qslaw"), how do I make sure the model is loaded as 4 bits? It seems that when I check model.model.layers[0].self_attn.q_proj.base_layer.weight.dtype, it still returns float32 instead of the reported 4 bits. Is there code to evaluate the model in the quantized state?
<img width="558" alt="Screenshot 2024-11-26 at 8 45 55 PM" src="https://github.com/user-attachments/assets/5d031985-66de-43e6-b28e-99ff017fa315">

**Comment by xjjxmu** [comment]
The llm weights in `llava-v1.5-vicuna-13b-v1.5-13b-chat-qslaw` are dequantized weights, to avoid frequent quantization-dequantization operations during evaluation. We appreciate your suggestion and will integrate Linear4bit in the future.

**Comment by xingyifei2016** [comment]
Is there sample code to convert these weights to 4 bits for evaluation? I am trying to reproduce the results by evaluating using the 4 bit model instead of the full precision model. Greatly appreciate your help.

**Comment by xjjxmu** [comment]
You can follow the line 279-313 in omniquant.py from [OmniQuant](https://github.com/OpenGVLab/OmniQuant/blob/main/quantize/omniquant.py) and contributions to our repository are highly welcome!
